version: 2

sources:
  - name: users_cars
    description: The table that has the data about the users and their cars.
    database: dbt
    schema : airbytes_schema
    tables:
      - name: users_cars

  - name : users_cars_two
    description: The table that has the data about the users and their cars.
    database: dbt
    schema : airbytes_schema
    tables:
      - name: users_cars
        
            

